// Generated by the gRPC protobuf plugin.
// If you make any local change, they will be lost.
// source: data_streamer.proto

#include "data_streamer.pb.h"
#include "data_streamer.grpc.pb.h"

#include <grpc++/impl/codegen/async_stream.h>
#include <grpc++/impl/codegen/async_unary_call.h>
#include <grpc++/impl/codegen/channel_interface.h>
#include <grpc++/impl/codegen/client_unary_call.h>
#include <grpc++/impl/codegen/method_handler_impl.h>
#include <grpc++/impl/codegen/rpc_service_method.h>
#include <grpc++/impl/codegen/service_type.h>
#include <grpc++/impl/codegen/sync_stream.h>

static const char* DataStreamer_method_names[] = {
  "/DataStreamer/RequestData",
};

std::unique_ptr< DataStreamer::Stub> DataStreamer::NewStub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options) {
  std::unique_ptr< DataStreamer::Stub> stub(new DataStreamer::Stub(channel));
  return stub;
}

DataStreamer::Stub::Stub(const std::shared_ptr< ::grpc::ChannelInterface>& channel)
  : channel_(channel), rpcmethod_RequestData_(DataStreamer_method_names[0], ::grpc::RpcMethod::SERVER_STREAMING, channel)
  {}

::grpc::ClientReader< ::Reply>* DataStreamer::Stub::RequestDataRaw(::grpc::ClientContext* context, const ::Request& request) {
  return new ::grpc::ClientReader< ::Reply>(channel_.get(), rpcmethod_RequestData_, context, request);
}

::grpc::ClientAsyncReader< ::Reply>* DataStreamer::Stub::AsyncRequestDataRaw(::grpc::ClientContext* context, const ::Request& request, ::grpc::CompletionQueue* cq, void* tag) {
  return new ::grpc::ClientAsyncReader< ::Reply>(channel_.get(), cq, rpcmethod_RequestData_, context, request, tag);
}

DataStreamer::Service::Service() {
  (void)DataStreamer_method_names;
  AddMethod(new ::grpc::RpcServiceMethod(
      DataStreamer_method_names[0],
      ::grpc::RpcMethod::SERVER_STREAMING,
      new ::grpc::ServerStreamingHandler< DataStreamer::Service, ::Request, ::Reply>(
          std::mem_fn(&DataStreamer::Service::RequestData), this)));
}

DataStreamer::Service::~Service() {
}

::grpc::Status DataStreamer::Service::RequestData(::grpc::ServerContext* context, const ::Request* request, ::grpc::ServerWriter< ::Reply>* writer) {
  (void) context;
  (void) request;
  (void) writer;
  return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
}


