// Generated by the gRPC protobuf plugin.
// If you make any local change, they will be lost.
// source: grgrpc.proto
#ifndef GRPC_grgrpc_2eproto__INCLUDED
#define GRPC_grgrpc_2eproto__INCLUDED

#include "grgrpc.pb.h"

#include <grpc++/impl/codegen/async_stream.h>
#include <grpc++/impl/codegen/async_unary_call.h>
#include <grpc++/impl/codegen/method_handler_impl.h>
#include <grpc++/impl/codegen/proto_utils.h>
#include <grpc++/impl/codegen/rpc_method.h>
#include <grpc++/impl/codegen/service_type.h>
#include <grpc++/impl/codegen/status.h>
#include <grpc++/impl/codegen/stub_options.h>
#include <grpc++/impl/codegen/sync_stream.h>

namespace grpc {
class CompletionQueue;
class Channel;
class RpcService;
class ServerCompletionQueue;
class ServerContext;
}  // namespace grpc

namespace grgrpc {

class GNURadioLink final {
 public:
  class StubInterface {
   public:
    virtual ~StubInterface() {}
    std::unique_ptr< ::grpc::ClientReaderWriterInterface< ::grgrpc::GRData, ::grgrpc::StatusData>> PublishData(::grpc::ClientContext* context) {
      return std::unique_ptr< ::grpc::ClientReaderWriterInterface< ::grgrpc::GRData, ::grgrpc::StatusData>>(PublishDataRaw(context));
    }
    std::unique_ptr< ::grpc::ClientAsyncReaderWriterInterface< ::grgrpc::GRData, ::grgrpc::StatusData>> AsyncPublishData(::grpc::ClientContext* context, ::grpc::CompletionQueue* cq, void* tag) {
      return std::unique_ptr< ::grpc::ClientAsyncReaderWriterInterface< ::grgrpc::GRData, ::grgrpc::StatusData>>(AsyncPublishDataRaw(context, cq, tag));
    }
    std::unique_ptr< ::grpc::ClientReaderWriterInterface< ::grgrpc::StatusData, ::grgrpc::GRData>> RequestData(::grpc::ClientContext* context) {
      return std::unique_ptr< ::grpc::ClientReaderWriterInterface< ::grgrpc::StatusData, ::grgrpc::GRData>>(RequestDataRaw(context));
    }
    std::unique_ptr< ::grpc::ClientAsyncReaderWriterInterface< ::grgrpc::StatusData, ::grgrpc::GRData>> AsyncRequestData(::grpc::ClientContext* context, ::grpc::CompletionQueue* cq, void* tag) {
      return std::unique_ptr< ::grpc::ClientAsyncReaderWriterInterface< ::grgrpc::StatusData, ::grgrpc::GRData>>(AsyncRequestDataRaw(context, cq, tag));
    }
  private:
    virtual ::grpc::ClientReaderWriterInterface< ::grgrpc::GRData, ::grgrpc::StatusData>* PublishDataRaw(::grpc::ClientContext* context) = 0;
    virtual ::grpc::ClientAsyncReaderWriterInterface< ::grgrpc::GRData, ::grgrpc::StatusData>* AsyncPublishDataRaw(::grpc::ClientContext* context, ::grpc::CompletionQueue* cq, void* tag) = 0;
    virtual ::grpc::ClientReaderWriterInterface< ::grgrpc::StatusData, ::grgrpc::GRData>* RequestDataRaw(::grpc::ClientContext* context) = 0;
    virtual ::grpc::ClientAsyncReaderWriterInterface< ::grgrpc::StatusData, ::grgrpc::GRData>* AsyncRequestDataRaw(::grpc::ClientContext* context, ::grpc::CompletionQueue* cq, void* tag) = 0;
  };
  class Stub final : public StubInterface {
   public:
    Stub(const std::shared_ptr< ::grpc::ChannelInterface>& channel);
    std::unique_ptr< ::grpc::ClientReaderWriter< ::grgrpc::GRData, ::grgrpc::StatusData>> PublishData(::grpc::ClientContext* context) {
      return std::unique_ptr< ::grpc::ClientReaderWriter< ::grgrpc::GRData, ::grgrpc::StatusData>>(PublishDataRaw(context));
    }
    std::unique_ptr<  ::grpc::ClientAsyncReaderWriter< ::grgrpc::GRData, ::grgrpc::StatusData>> AsyncPublishData(::grpc::ClientContext* context, ::grpc::CompletionQueue* cq, void* tag) {
      return std::unique_ptr< ::grpc::ClientAsyncReaderWriter< ::grgrpc::GRData, ::grgrpc::StatusData>>(AsyncPublishDataRaw(context, cq, tag));
    }
    std::unique_ptr< ::grpc::ClientReaderWriter< ::grgrpc::StatusData, ::grgrpc::GRData>> RequestData(::grpc::ClientContext* context) {
      return std::unique_ptr< ::grpc::ClientReaderWriter< ::grgrpc::StatusData, ::grgrpc::GRData>>(RequestDataRaw(context));
    }
    std::unique_ptr<  ::grpc::ClientAsyncReaderWriter< ::grgrpc::StatusData, ::grgrpc::GRData>> AsyncRequestData(::grpc::ClientContext* context, ::grpc::CompletionQueue* cq, void* tag) {
      return std::unique_ptr< ::grpc::ClientAsyncReaderWriter< ::grgrpc::StatusData, ::grgrpc::GRData>>(AsyncRequestDataRaw(context, cq, tag));
    }

   private:
    std::shared_ptr< ::grpc::ChannelInterface> channel_;
    ::grpc::ClientReaderWriter< ::grgrpc::GRData, ::grgrpc::StatusData>* PublishDataRaw(::grpc::ClientContext* context) override;
    ::grpc::ClientAsyncReaderWriter< ::grgrpc::GRData, ::grgrpc::StatusData>* AsyncPublishDataRaw(::grpc::ClientContext* context, ::grpc::CompletionQueue* cq, void* tag) override;
    ::grpc::ClientReaderWriter< ::grgrpc::StatusData, ::grgrpc::GRData>* RequestDataRaw(::grpc::ClientContext* context) override;
    ::grpc::ClientAsyncReaderWriter< ::grgrpc::StatusData, ::grgrpc::GRData>* AsyncRequestDataRaw(::grpc::ClientContext* context, ::grpc::CompletionQueue* cq, void* tag) override;
    const ::grpc::RpcMethod rpcmethod_PublishData_;
    const ::grpc::RpcMethod rpcmethod_RequestData_;
  };
  static std::unique_ptr<Stub> NewStub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options = ::grpc::StubOptions());

  class Service : public ::grpc::Service {
   public:
    Service();
    virtual ~Service();
    virtual ::grpc::Status PublishData(::grpc::ServerContext* context, ::grpc::ServerReaderWriter< ::grgrpc::StatusData, ::grgrpc::GRData>* stream);
    virtual ::grpc::Status RequestData(::grpc::ServerContext* context, ::grpc::ServerReaderWriter< ::grgrpc::GRData, ::grgrpc::StatusData>* stream);
  };
  template <class BaseClass>
  class WithAsyncMethod_PublishData : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service *service) {}
   public:
    WithAsyncMethod_PublishData() {
      ::grpc::Service::MarkMethodAsync(0);
    }
    ~WithAsyncMethod_PublishData() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status PublishData(::grpc::ServerContext* context, ::grpc::ServerReaderWriter< ::grgrpc::StatusData, ::grgrpc::GRData>* stream) final override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void RequestPublishData(::grpc::ServerContext* context, ::grpc::ServerAsyncReaderWriter< ::grgrpc::StatusData, ::grgrpc::GRData>* stream, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncBidiStreaming(0, context, stream, new_call_cq, notification_cq, tag);
    }
  };
  template <class BaseClass>
  class WithAsyncMethod_RequestData : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service *service) {}
   public:
    WithAsyncMethod_RequestData() {
      ::grpc::Service::MarkMethodAsync(1);
    }
    ~WithAsyncMethod_RequestData() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status RequestData(::grpc::ServerContext* context, ::grpc::ServerReaderWriter< ::grgrpc::GRData, ::grgrpc::StatusData>* stream) final override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void RequestRequestData(::grpc::ServerContext* context, ::grpc::ServerAsyncReaderWriter< ::grgrpc::GRData, ::grgrpc::StatusData>* stream, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncBidiStreaming(1, context, stream, new_call_cq, notification_cq, tag);
    }
  };
  typedef WithAsyncMethod_PublishData<WithAsyncMethod_RequestData<Service > > AsyncService;
  template <class BaseClass>
  class WithGenericMethod_PublishData : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service *service) {}
   public:
    WithGenericMethod_PublishData() {
      ::grpc::Service::MarkMethodGeneric(0);
    }
    ~WithGenericMethod_PublishData() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status PublishData(::grpc::ServerContext* context, ::grpc::ServerReaderWriter< ::grgrpc::StatusData, ::grgrpc::GRData>* stream) final override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
  };
  template <class BaseClass>
  class WithGenericMethod_RequestData : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service *service) {}
   public:
    WithGenericMethod_RequestData() {
      ::grpc::Service::MarkMethodGeneric(1);
    }
    ~WithGenericMethod_RequestData() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status RequestData(::grpc::ServerContext* context, ::grpc::ServerReaderWriter< ::grgrpc::GRData, ::grgrpc::StatusData>* stream) final override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
  };
  typedef Service StreamedUnaryService;
  typedef Service SplitStreamedService;
  typedef Service StreamedService;
};

}  // namespace grgrpc


#endif  // GRPC_grgrpc_2eproto__INCLUDED
